### ISSUE TITLE
Thank you for this package!

### ISSUE THREAD

**Issue by harzkr** [webcarrot/xirr#1]
This package works very accurately and in contrast to all other XIRR packages which had some issue or the other, either in values being calculated or in convergence, this package handles all types of calculations very very well!!

Thank you so much @webcarrot !

**Comment by webcarrot** [comment]
Thanks.  

I had same problems with other existing implementations (written in many languages) - they return correct values only if we assume that Newton-Raphson-Whatever definition of the XIRR function is correct one 😉 

Anyway - i only stole algorithm from LibreOffice codebase and implement it in TypeScript - no big deal.
